### ISSUE TITLE
A lot of panics in latest version

### ISSUE THREAD

**Issue by Snawoot** [maticnetwork/bor#1012]
#### **System information**

Bor client version: v1.0.4
Heimdall client version: v1.0.1

OS & Version: Linux

Environment: Polygon Mainnet

Type of node: Sentry

Additional Information: 

#### **Overview of the problem**

A lot of panic messages in the bor log.

#### **Reproduction Steps**

Not sure, it seems handler panics on some eth_calls

#### **Logs / Traces / Output / Error Messages**
 
```
Sep 20 19:17:46 matic-full-node-de-1 bor[3351]: ERROR[09-20|19:17:46.593] RPC method eth_call crashed: runtime error: invalid memory ad
dress or nil pointer dereference
Sep 20 19:17:46 matic-full-node-de-1 bor[3351]: goroutine 14638 [running]:
Sep 20 19:17:46 matic-full-node-de-1 bor[3351]: github.com/ethereum/go-ethereum/rpc.(*callback).call.func1()
Sep 20 19:17:46 matic-full-node-de-1 bor[3351]:         /home/runner/work/bor/bor/rpc/service.go:217 +0x89
Sep 20 19:17:46 matic-full-node-de-1 bor[3351]: panic({0x24fede0, 0x486e290})
Sep 20 19:17:46 matic-full-node-de-1 bor[3351]:         /opt/hostedtoolcache/go/1.20.8/x64/src/runtime/panic.go:884 +0x213
Sep 20 19:17:46 matic-full-node-de-1 bor[3351]: github.com/ethereum/go-ethereum/core/types.(*Block).Header(...)
Sep 20 19:17:46 matic-full-node-de-1 bor[3351]:         /home/runner/work/bor/bor/core/types/block.go:465
Sep 20 19:17:46 matic-full-node-de-1 bor[3351]: github.com/ethereum/go-ethereum/eth.(*EthAPIBackend).StateAndHeaderByNumber(0xc02af1d050?, {0x358f180?, 0xc024d5b7c0?}, 0xc024d5ae60?)
Sep 20 19:17:46 matic-full-node-de-1 bor[3351]:         /home/runner/work/bor/bor/eth/api_backend.go:220 +0x111
Sep 20 19:17:46 matic-full-node-de-1 bor[3351]: github.com/ethereum/go-ethereum/eth.(*EthAPIBackend).StateAndHeaderByNumberOrHash(0xc02c623830?, {0x358f180?, 0xc024d5b7c0?}, {0xc0208f9590, 0x0, 0x0})
Sep 20 19:17:46 matic-full-node-de-1 bor[3351]:         /home/runner/work/bor/bor/eth/api_backend.go:239 +0x2ed
Sep 20 19:17:46 matic-full-node-de-1 bor[3351]: github.com/ethereum/go-ethereum/internal/ethapi.DoCall({0x358f180, 0xc024d5b7c0}, {0x35c2758?, 0xc0156da978?}, {0xc02c623b60, 0xc02c623b78, 0x0, 0x0, 0x0, 0x0, ...}, ...)
Sep 20 19:17:46 matic-full-node-de-1 bor[3351]:         /home/runner/work/bor/bor/internal/ethapi/api.go:1160 +0x2f8
Sep 20 19:17:46 matic-full-node-de-1 bor[3351]: github.com/ethereum/go-ethereum/internal/ethapi.(*BlockChainAPI).CallWithState(0xc0018feba0, {0x358f180, 0xc024d5b7c0}, {0xc02c623b60, 0xc02c623b78, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
Sep 20 19:17:46 matic-full-node-de-1 bor[3351]:         /home/runner/work/bor/bor/internal/ethapi/api.go:1285 +0x132
Sep 20 19:17:46 matic-full-node-de-1 bor[3351]: github.com/ethereum/go-ethereum/internal/ethapi.(*BlockChainAPI).Call(0xc001668000?, {0x358f180?, 0xc024d5b7c0?}, {0xc02c623b60, 0xc02c623b78, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
Sep 20 19:17:46 matic-full-node-de-1 bor[3351]:         /home/runner/work/bor/bor/internal/ethapi/api.go:1272 +0x85
Sep 20 19:17:46 matic-full-node-de-1 bor[3351]: reflect.Value.call({0xc02aecf340?, 0xc02aef8fb8?, 0x7f6db85f71b8?}, {0x28d6658, 0x4}, {0xc01954b100, 0x5, 0x0?})
```

Larger log fragment: [panic.log.gz](https://github.com/maticnetwork/bor/files/12676397/panic.log.gz)

**Additional Information**

```
root@matic-full-node-de-1 ~ # systemctl cat bor.service
# /lib/systemd/system/bor.service
[Unit]
  Description=bor
  StartLimitIntervalSec=500
  StartLimitBurst=5

[Service]
  Restart=on-failure
  RestartSec=5s
  ExecStart=/usr/bin/bor server -config "/var/lib/bor/config.toml"
  Type=simple
  KillSignal=SIGINT
  User=bor
  TimeoutStopSec=120

[Install]
  WantedBy=multi-user.target

# /etc/systemd/system/bor.service.d/override.conf
[Service]
  ExecStart=
  ExecStart=/usr/bin/bor server -config /data/.bor/config.toml
```

```
> eth.syncing
{
  currentBlock: 47778139,
  healedBytecodeBytes: 0,
  healedBytecodes: 0,
  healedTrienodeBytes: 0,
  healedTrienodes: 0,
  healingBytecode: 0,
  healingTrienodes: 0,
  highestBlock: 47778142,
  startingBlock: 47778139,
  syncedAccountBytes: 0,
  syncedAccounts: 0,
  syncedBytecodeBytes: 0,
  syncedBytecodes: 0,
  syncedStorage: 0,
  syncedStorageBytes: 0
}
```

**Comment by cffls** [comment]
Thanks @Snawoot  for reporting this issue. Could you provide any sample RPC request that caused panic? Also, did the node panic and stop running, or did it continue to run even with these logs?

**Comment by Snawoot** [comment]
@cffls I cant provide sample RPC request, the node is running on public interface and most likely it's some stray requests from outside.

Node continued to run, it seems panic in handler was `recover()`ed.

**Comment by cffls** [comment]
Thanks for the quick response. Could you provide the full trace of panic?

**Comment by Snawoot** [comment]
@cffls Sure! Here is compressed log excerpt with a lot of such panics.
[panic.log.gz](https://github.com/maticnetwork/bor/files/12676397/panic.log.gz)

**Comment by cffls** [comment]
Thanks, this is really helpful. Looks like the failed RPC call was requesting "pending" block, which is only available on miners: https://github.com/maticnetwork/bor/blob/2943db974dbb7a19ffbc4eb29aa611a85e759229/eth/api_backend.go#L220

If your node is not running as a miner, this error seems expected.

**Comment by PeaStew** [comment]
@cffls it is normal to have a panic on a call not supported by bor?
