### ISSUE TITLE
bor 1.0.4-fh2.3 (firehose version) crash on block 38,820,338

### ISSUE THREAD

**Issue by matthewdarwin** [maticnetwork/bor#1017]
bor 1.0.4 crash when replaying old blocks, get a stack trace after block 38,820,338
heimdall version 0.3.4

Note have replayed many other blocks from genesis, this is first crash after 1 week of testing.

````
2023-09-25T16:18:55.562Z INFO (reader.geth) fetching state sync events               queryParams="from-id=2562924&to-time=1675336044&limit=50"
2023-09-25T16:18:55.738Z WARN (reader.geth) an error while trying fetching from Heimdall attempt=1 error="error while fetching data from Heimdall: response code 404"
2023-09-25T16:18:55.738Z INFO (reader.geth) retrying again in 5 seconds to fetch data from Heimdall path=/milestone/lastNoAck    attempt=1
2023-09-25T16:18:57.190Z INFO (reader.geth) stateSyncData                            gas=0         number=38,820,336 lastStateID=2,562,923 "total records"=0  "fetch time"=1627  "process time"=0
2023-09-25T16:18:57.191Z INFO (reader.geth) retrying again in 5 seconds to fetch data from Heimdall path=/milestone/latest       attempt=2
2023-09-25T16:18:57.294Z INFO (reader.geth) imported new chain segment               number=38,820,336 hash=308096..e52c5b blocks=17   txs=1454    mgas=269.035 elapsed=9.500s  mgasps=28.319 age=7mo3w4d  dirty=589.21MiB
2023-09-25T16:18:57.771Z INFO (reader.geth) s.allocCount= 57 s.nelems= 9
2023-09-25T16:18:57.771Z INFO (reader.geth) fatal error: s.allocCount > s.nelems
2023-09-25T16:18:57.773Z INFO (reader.geth) goroutine 57362 [running]:
2023-09-25T16:18:57.773Z INFO (reader.geth) runtime.throw({0x27e1758?, 0xc14aa1c313?})
2023-09-25T16:18:57.773Z INFO (reader.geth) #011/usr/local/go-1.21.1/src/runtime/panic.go:1077 +0x5c fp=0xc04cfdabd0 sp=0xc04cfdaba0 pc=0x44c17c
2023-09-25T16:18:57.773Z INFO (reader.geth) runtime.(*mcache).nextFree(0x7fc70a93cf58, 0x13)
2023-09-25T16:18:57.773Z INFO (reader.geth) #011/usr/local/go-1.21.1/src/runtime/malloc.go:940 +0x156 fp=0xc04cfdac18 sp=0xc04cfdabd0 pc=0x420896
2023-09-25T16:18:57.773Z INFO (reader.geth) runtime.mallocgc(0x6a, 0x0, 0x0)
2023-09-25T16:18:57.773Z INFO (reader.geth) #011/usr/local/go-1.21.1/src/runtime/malloc.go:1112 +0x448 fp=0xc04cfdac80 sp=0xc04cfdac18 pc=0x420d88
2023-09-25T16:18:57.773Z INFO (reader.geth) internal/bytealg.MakeNoZero(0x6a)
2023-09-25T16:18:57.773Z INFO (reader.geth) #011/usr/local/go-1.21.1/src/runtime/slice.go:354 +0x2b fp=0xc04cfdaca8 sp=0xc04cfdac80 pc=0x47f30b
2023-09-25T16:18:57.773Z INFO (reader.geth) strings.(*Builder).grow(0xc04cfdad88, 0x10?)
2023-09-25T16:18:57.773Z INFO (reader.geth) #011/usr/local/go-1.21.1/src/strings/builder.go:69 +0x27 fp=0xc04cfdace8 sp=0xc04cfdaca8 pc=0x4d8027
2023-09-25T16:18:57.773Z INFO (reader.geth) strings.(*Builder).Grow(0x0?, 0xc04cfdad40?)
2023-09-25T16:18:57.773Z INFO (reader.geth) #011/usr/local/go-1.21.1/src/strings/builder.go:83 +0x50 fp=0xc04cfdad08 sp=0xc04cfdace8 pc=0x4d8130
2023-09-25T16:18:57.773Z INFO (reader.geth) strings.Join({0xc1bbc345b0?, 0x7, 0x7}, {0x3428550, 0x1})
2023-09-25T16:18:57.773Z INFO (reader.geth) #011/usr/local/go-1.21.1/src/strings/strings.go:457 +0x113 fp=0xc04cfdadb8 sp=0xc04cfdad08 pc=0x4dcef3
2023-09-25T16:18:57.773Z INFO (reader.geth) github.com/ethereum/go-ethereum/firehose.(*ToBufferPrinter).Print(0xc19e16c330, {0xc1bbc345b0?, 0x28?, 0xc19a4930b0?})
2023-09-25T16:18:57.773Z INFO (reader.geth) #011/tmp/build.1695216549.1821921/go-ethereum/firehose/printer.go:106 +0x32 fp=0xc04cfdae28 sp=0xc04cfdadb8 pc=0xd06292
2023-09-25T16:18:57.773Z INFO (reader.geth) github.com/ethereum/go-ethereum/firehose.(*Context).RecordBalanceChange(0xc1c9bd2930, {0x73, 0xc6, 0x2e, 0xd2, 0xf6, 0xf9, 0xa5, 0xdc, 0xd, ...}, ...)
2023-09-25T16:18:57.773Z INFO (reader.geth) #011/tmp/build.1695216549.1821921/go-ethereum/firehose/context.go:662 +0x2f4 fp=0xc04cfdaed0 sp=0xc04cfdae28 pc=0xd02b74
2023-09-25T16:18:57.773Z INFO (reader.geth) github.com/ethereum/go-ethereum/core/state.(*stateObject).SetBalance(0xc1ad54a410, 0xc1650ddfe0, 0xb3cbae15d2ad4a0d?, {0x27bdfbb?, 0xc1a0ca7398?})
2023-09-25T16:18:57.773Z INFO (reader.geth) #011/tmp/build.1695216549.1821921/go-ethereum/core/state/state_object.go:446 +0x7b fp=0xc04cfdaf88 sp=0xc04cfdaed0 pc=0xd2f6fb
```

**Comment by matthewdarwin** [comment]
Full log files
[polygon.log](https://github.com/maticnetwork/bor/files/12717669/polygon.log)

**Comment by marcello33** [comment]
@matthewdarwin any update? Otherwise we can proceed closing the issue.
Thanks

**Comment by manav2401** [comment]
Closing this for now, feel free to reopen.
