### ISSUE TITLE
Bor crashes with fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by aaa8212** [maticnetwork/bor#1181]
#### **System information**

Bor client version: 1.2.3

Heimdall client version: 1.0.3

OS & Version: Linux

Environment: Polygon Mainnet

Type of node: Archive

Additional Information: /

#### **Overview of the problem**

Our bor process has restarted, losing >1d of latest data in the process. The start of problems is this entry in logs:
```
bor_1             | WARN [03-08|14:32:48.172] Peer delivering stale transactions       peer=d9b4f4be05ca8483cf0f059be9eaaf1da9d6d794e6edbe57a55fbe5edc3b9730 rejected=54
bor_1             | fatal error: concurrent map read and map write
bor_1             |
bor_1             | goroutine 1063580682 [running]:
bor_1             | github.com/ethereum/go-ethereum/core/state.(*stateObject).GetCommittedState(0xc08982e1c0, {0x18, 0x3c, 0xde, 0x5d, 0x4f, 0x6b, 0xb7, 0xb4, 0x45, ...})
bor_1             |     /go/src/github.com/maticnetwork/bor/core/state/state_object.go:183 +0xa5
bor_1             | github.com/ethereum/go-ethereum/core/state.(*stateObject).GetState(...)
bor_1             |     /go/src/github.com/maticnetwork/bor/core/state/state_object.go:173
bor_1             | github.com/ethereum/go-ethereum/core/state.(*StateDB).GetState.func1(0x7522161dfdd0157f?)
bor_1             |     /go/src/github.com/maticnetwork/bor/core/state/statedb.go:667 +0x135
bor_1             | github.com/ethereum/go-ethereum/core/state.MVRead[...](0xc110f4b000?, {0x3c, 0xd7, 0xd8, 0xe8, 0x98, 0x7b, 0x7b, 0xce, 0x47, ...}, ...)
bor_1             |     /go/src/github.com/maticnetwork/bor/core/state/statedb.go:318 +0x399
bor_1             | github.com/ethereum/go-ethereum/core/state.(*StateDB).GetState(0x0?, {0x3c, 0xd7, 0xd8, 0xe8, 0x98, 0x7b, 0x7b, 0xce, 0x47, ...}, ...)
bor_1             |     /go/src/github.com/maticnetwork/bor/core/state/statedb.go:664 +0x17d
```

#### **Reproduction Steps**

Sorry, can't help much here - it happened a week ago. then was running stable (the same version), now the crash happened again.

#### **Logs / Traces / Output / Error Messages**

**Additional Information**

**Comment by aaa8212** [comment]
Thank you for fast response! I have missed this issue in search. Thanks, will upgrade - since the issue is difficult to reproduce anyway, I'll close this ticket and reopen if it happens again with 1.2.7.

Thank you again!
