### ISSUE TITLE
segmentation violation

### ISSUE THREAD

**Issue by unek** [maticnetwork/bor#321]
#### System information

Geth version: 0.2.14-stable
OS & Version: Linux Ubuntu 20.04.3 LTS

#### Expected behaviour
not crashing

#### Actual behaviour
crashing

#### Steps to reproduce the behaviour
get the snapshot from https://snapshots.matic.today/ & run with
```
--datadir $DATA_DIR \
  --bor-mainnet \
  --port 30305 \
  --http --http.port 10545 \
  --http.vhosts '*' \
  --http.corsdomain '*' \
  --ipcpath $DATA_DIR/bor.ipc \
  --http.api 'debug,eth,net,web3,txpool,bor' \
  --syncmode 'snap' \
  --bootnodes "enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303,enode://3178257cd1e1ab8f95eeb7cc45e28b6047a0432b2f9412cff1db9bb31426eac30edeb81fedc30b7cd3059f0902b5350f75d1b376d2c632e1b375af0553813e6f@35.221.13.28:30303,enode://16d9a28eadbd247a09ff53b7b1f22231f6deaf10b86d4b23924023aea49bfdd51465b36d79d29be46a5497a96151a1a1ea448f8a8666266284e004306b2afb6e@35.199.4.13:30303,enode://ef271e1c28382daa6ac2d1006dd1924356cfd843dbe88a7397d53396e0741ca1a8da0a113913dee52d9071f0ad8d39e3ce87aa81ebc190776432ee7ddc9d9470@35.230.116.151:30303"
```

#### Backtrace

````
INFO [02-05|17:07:17.548] → committing new state                   eventRecord="id 1606904, contract 0xA6FA4fB5f76172d178d61B04b0ecd319C5d1C0aa, data: 0x87a7811f4bfedea3d341ad165680ae306b01aaeacc205d227629cf157dd9f821000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000988ba2b1ae9ea797a094ca6fcde4ff4bd30e93ee000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee00000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000221b262dd8000, txHash: 0x91aa286e7f33e4ddc849f8f70ec045a0d47af012ee40ab5b18c5d6f98364f5db, logIndex: 240, chainId: 137, time 2022-02-05T15:56:09Z"
INFO [02-05|17:07:17.568] Skip duplicated bad block                number=24,585,088 hash=60f1f9..627925
ERROR[02-05|17:07:17.570]
########## BAD BLOCK #########
Chain config: {ChainID: 137 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: 23850000, Engine: bor}

Number: 24585088
Hash: 0x60f1f9abad5d54f2cb8f29601c0114972d9ddaecabbdd797a299e4f184627925
         0: cumulative: 29373 gas: 29373 contract: 0x0000000000000000000000000000000000000000 status: 0 tx: 0xfadd2ecea8961ac8fff2b59d52a24e7d7667d1fcf18f065dcd31956146dd4d85 logs: [0xc009dd80b0] bloom: 00000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000008000000000000000000000000001000000000000000000000000000000800000000000000000000100000000000000000000000040000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000001000000000000200000000000000000000000000000000000000000000000000000000000004000000000000000000001000040000000000000000000000000100000000000000000000000000000000000000000000000000000000000000008000000100000 state:


...

Error: invalid merkle root (remote: daf49602d8f40058e9b65c9d1bcb46b2fe6ba6477aec42ce877af7c15de5e933 local: bda0cc7a2b6ead4be6e3a1ebe8c6d8fd7217a3f37f3dec51413f07a4be297ef9)                            [10766/49877]##############################

WARN [02-05|17:07:17.572] Synchronisation failed, dropping peer    peer=5efde90c8cc98b479c6ce0c01f4d58cbf64200a39caac2de4e1e77894b05748c err="retrieved hash chain is invalid: invalid merkle root (remote: daf49602d8f40058e9b65c9d1bcb46b2fe6ba6477aec42ce877af7c15de5e933 local: bda0cc7a2b6ead4be6e3a1ebe8c6d8fd7217a3f37f3dec51413f07a4be297ef9)"
WARN [02-05|17:07:17.572] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [02-05|17:07:20.546] Imported new chain segment               blocks=1     txs=192       mgas=29.989   elapsed=187.281ms   mgasps=160.127 number=24,585,111 hash=780223..3821f8 dirty=819.08MiB
INFO [02-05|17:07:20.547] Unindexed transactions                   blocks=1     txs=60        tail=22,235,112 elapsed=1.049ms
INFO [02-05|17:07:30.534] Imported new chain segment               blocks=1     txs=207       mgas=29.996   elapsed=172.326ms   mgasps=174.063 number=24,585,112 hash=fad741..e6d4f7 dirty=820.05MiB
INFO [02-05|17:07:30.535] Unindexed transactions                   blocks=1     txs=59        tail=22,235,113 elapsed=1.023ms
INFO [02-05|17:07:30.636] Deep froze chain segment                 blocks=6     elapsed=4.364ms     number=24,495,112 hash=e10fdd..53138e
ERROR[02-05|17:07:32.114] Snapshot extension registration failed   peer=e8de2f6e err="peer connected on snap without compatible eth support"
ERROR[02-05|17:07:39.782] Snapshot extension registration failed   peer=7b2965b1 err="peer connected on snap without compatible eth support"
INFO [02-05|17:07:40.540] Imported new chain segment               blocks=1     txs=132       mgas=29.999   elapsed=155.889ms   mgasps=192.437 number=24,585,113 hash=83a79b..159d06 dirty=820.73MiB
INFO [02-05|17:07:40.541] Unindexed transactions                   blocks=1     txs=43        tail=22,235,114 elapsed="761.052µs"
ERROR[02-05|17:07:40.665] Snapshot extension registration failed   peer=0f8f49f1 err="peer connected on snap without compatible eth support"
ERROR[02-05|17:07:50.372] Snapshot extension registration failed   peer=ac71ceaa err="peer connected on snap without compatible eth support"
INFO [02-05|17:07:50.673] Imported new chain segment               blocks=1     txs=179       mgas=29.985   elapsed=172.419ms   mgasps=173.906 number=24,585,114 hash=a0ce85..d825a2 dirty=821.98MiB
INFO [02-05|17:07:50.674] Unindexed transactions                   blocks=1     txs=45        tail=22,235,115 elapsed="928.286µs"
INFO [02-05|17:08:00.443] Imported new chain segment               blocks=1     txs=263       mgas=29.991   elapsed=184.451ms   mgasps=162.594 number=24,585,115 hash=68603f..6ac1ff dirty=823.44MiB
INFO [02-05|17:08:00.445] Unindexed transactions                   blocks=1     txs=61        tail=22,235,116 elapsed=1.213ms
INFO [02-05|17:08:10.542] Imported new chain segment               blocks=1     txs=197       mgas=29.981   elapsed=198.992ms   mgasps=150.665 number=24,585,116 hash=672f6e..f522e6 dirty=825.21MiB
INFO [02-05|17:08:10.544] Unindexed transactions                   blocks=1     txs=56        tail=22,235,117 elapsed=1.092ms
INFO [02-05|17:08:20.528] Imported new chain segment               blocks=1     txs=144       mgas=29.985   elapsed=255.742ms   mgasps=117.245 number=24,585,117 hash=557982..8be17f dirty=826.48MiB
INFO [02-05|17:08:20.530] Unindexed transactions                   blocks=1     txs=50        tail=22,235,118 elapsed="906.234µs"
ERROR[02-05|17:08:22.855] Snapshot extension registration failed   peer=cbd3f861 err="peer connected on snap without compatible eth support"
ERROR[02-05|17:08:28.536] Snapshot extension registration failed   peer=2fe4e589 err="peer connected on snap without compatible eth support"
INFO [02-05|17:08:30.535] Imported new chain segment               blocks=1     txs=209       mgas=29.990   elapsed=216.999ms   mgasps=138.202 number=24,585,118 hash=44e672..c3392e dirty=828.27MiB
INFO [02-05|17:08:30.536] Unindexed transactions                   blocks=1     txs=52        tail=22,235,119 elapsed=1.317ms
INFO [02-05|17:08:30.642] Deep froze chain segment                 blocks=6     elapsed=4.241ms     number=24,495,118 hash=0101e6..c2903e
ERROR[02-05|17:08:36.876] Snapshot extension registration failed   peer=7f8f9f13 err="peer connected on snap without compatible eth support"
INFO [02-05|17:08:40.705] Imported new chain segment               blocks=1     txs=208       mgas=29.976   elapsed=200.166ms   mgasps=149.754 number=24,585,119 hash=f32cb6..8eeb7b dirty=829.96MiB
INFO [02-05|17:08:40.706] Unindexed transactions                   blocks=1     txs=48        tail=22,235,120 elapsed=1.008ms
INFO [02-05|17:08:50.501] Imported new chain segment               blocks=1     txs=164       mgas=25.181   elapsed=177.862ms   mgasps=141.578 number=24,585,120 hash=d3ac92..9bb195 dirty=831.36MiB
INFO [02-05|17:08:50.502] Unindexed transactions                   blocks=1     txs=48        tail=22,235,121 elapsed="989.461µs"
INFO [02-05|17:09:00.768] Imported new chain segment               blocks=1     txs=139       mgas=29.993   elapsed=182.858ms   mgasps=164.021 number=24,585,121 hash=b94879..a449a5 dirty=833.52MiB
INFO [02-05|17:09:00.769] Unindexed transactions                   blocks=1     txs=52        tail=22,235,122 elapsed=1.011ms
INFO [02-05|17:09:09.734] Downloader queue stats                   receiptTasks=0 blockTasks=0     itemSize=96.54KiB throttle=2716
WARN [02-05|17:09:09.766] Caller gas above allowance, capping      requested=9,223,372,036,854,775,807 cap=50,000,000
WARN [02-05|17:09:09.766] Caller gas above allowance, capping      requested=9,223,372,036,854,775,807 cap=50,000,000
INFO [02-05|17:09:09.766] Fetching state updates from Heimdall     fromID=1,606,836 to=2022-02-05T17:01:10+01:00
INFO [02-05|17:09:09.766] Fetching state sync events               queryParams="from-id=1606836&to-time=1644076870&limit=50"
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x47 pc=0x7f7cfd2675ca]

runtime stack:
runtime.throw({0x15ffd49, 0x7f7c90000d64})
        /usr/local/go/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:719 +0x396

goroutine 3236556 [syscall]:
runtime.cgocall(0x1176c70, 0xc01909dd90)
        /usr/local/go/src/runtime/cgocall.go:156 +0x5c fp=0xc01909dd68 sp=0xc01909dd30 pc=0x40efbc
net._C2func_getaddrinfo(0xc086122800, 0x0, 0xc097a98780, 0xc04ba77eb0)
        _cgo_gotypes.go:91 +0x56 fp=0xc01909dd90 sp=0xc01909dd68 pc=0x636876
net.cgoLookupIPCNAME.func1({0xc086122800, 0x141f0e0, 0xc131633008}, 0xc0861227e0, 0xc01909de50)
        /usr/local/go/src/net/cgo_unix.go:163 +0x9f fp=0xc01909dde8 sp=0xc01909dd90 pc=0x6385bf
net.cgoLookupIPCNAME({0x15c4830, 0x3}, {0xc0861227e0, 0x4})
        /usr/local/go/src/net/cgo_unix.go:163 +0x16d fp=0xc01909df38 sp=0xc01909dde8 pc=0x637e0d
net.cgoIPLookup(0x2461510, {0x15c4830, 0xc0861227f0}, {0xc0861227e0, 0xc01d9a9600})
````

plus about 25,000 lines of stack trace.

happens every time after a few hours of running. didn't happen on 0.2.9.

**Comment by vcastellm** [comment]
Are you using packages or compiling from source?

**Comment by unek** [comment]
using the binary provided on the releases page

**Comment by yoongyy** [comment]
I face the same issue, from the 0.2.13 suddenly have this error, I then upgraded to 0.2.14 but still the same issue again...
Please help to fix it asap

**Comment by unek** [comment]
hasn't crashed for hours now on the latest 0.3.0 dev build

**Comment by vcastellm** [comment]
We detected a bug on the network stack at compilation time, it will be fixed and released in the upcoming `v0.2.15` in the following days, please, build from source in the meantime.

**Comment by PeaStew** [comment]
@vcastellm this issue persists with no new version in sight, we are encountering this issue on multiple nodes. When will it be fixed?

**Comment by 0xKrishna** [comment]
Let's try to build from source for now

**Comment by PeaStew** [comment]
To be clear, for anyone following up, using the provided 2.0.14 binaries (at least the .deb and probably the rest) does not include a fix for the above issues but the source code does. Therefore everyone needs to build from source and not use the binaries provided.

**Comment by vcastellm** [comment]
FYI binaries has been removed, we'll start releasing working binaries starting on the next release.
