### ISSUE TITLE
Bor start from fullnode-snapshot ,but appeared panic

### ISSUE THREAD

**Issue by julia-light** [maticnetwork/bor#345]
#### System information

Geth/Bor version: `0.2.14-stable`
OS & Version: `Linux`
Git Tags: `v0.2.14`
```
Version: 0.2.14-stable
Git Commit: 28963d5ccd3028e0ac6f1915845c747862d649d1
Architecture: amd64
Go Version: go1.17
Operating System: linux
GOPATH=/bv/go
GOROOT=/bv/.go
```

#### Expected behaviour
sync data from snapshot and write block data normally 

#### Steps to reproduce the behaviour
`wget snapshot:  wget -q -O - 'https://matic-blockchain-snapshots.s3-accelerate.amazonaws.com/matic-mainnet/bor-fullnode-snapshot-2022-02-20.tar.gz' | tar zxf - &
`
docker-compose.yml
```
version: '3.4'

services:
  bor:
    container_name: bor
    image: bor:latest
    build: /datarepo/bor
    volumes:
        - /data-bor/data/bor:/datadir
    ports:
        - "8545:8545" # RPC
        - "30303:30303" # Peers (TCP)
        - "30303:30303/udp" # Peers (UDP)
    command:
        - --bor-mainnet
        - --syncmode=full
        - --datadir=/datadir
        - --networkid=137
        - --bor.heimdall=http://heimdallr:1317
        - --bor.logs
        - --miner.gaslimit=200000000
        - --miner.gastarget=20000000
        - --http
        - --http.addr=0.0.0.0
        - --http.port=8545
        - --http.api=eth,net,web3,admin,debug,bor
        - --http.corsdomain=*
        - --http.vhosts=*
        - --ws
        - --ws.addr=0.0.0.0
        - --ws.port=8545
        - --ws.api=eth,net,web3,admin,debug,bor
        - --ws.origins=*
        - --ipcdisable
        - --nousb
        - --bootnodes=enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303
 ```
#### Backtrace

````
INFO [03-03|04:49:07.193] Starting pprof server                    addr=http://0.0.0.0:7071/debug/pprof
INFO [03-03|04:49:07.193] Starting Bor on Bor mainnet...
INFO [03-03|04:49:07.194] Maximum peer count                       ETH=200 LES=0 total=200
INFO [03-03|04:49:07.194] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [03-03|04:49:07.194] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable
WARN [03-03|04:49:07.194] The generic --miner.gastarget flag is deprecated and will be removed in the future!
INFO [03-03|04:49:07.194] Set global gas cap                       cap=50,000,000
INFO [03-03|04:49:07.195] Allocated trie memory caches             clean=154.00MiB dirty=256.00MiB
INFO [03-03|04:49:07.195] Allocated cache and file handles         database=/datadir/bor/chaindata cache=512.00MiB handles=32768
INFO [03-03|04:49:10.069] Opened ancient database                  database=/datadir/bor/chaindata/ancient readonly=false
INFO [03-03|04:49:10.236] Persisted trie from memory database      nodes=12 size=1.86KiB time="34.071µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [03-03|04:49:10.387] Initialised chain configuration          config="{ChainID: 137 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: 23850000, Engine: bor}"
INFO [03-03|04:49:11.932] Gasprice oracle is ignoring threshold set threshold=2
INFO [03-03|04:49:11.992] Initialising Ethereum protocol           network=137 dbversion=8
WARN [03-03|04:49:12.419] Head block missing, resetting chain      hash=bbe47c..ff4d8c
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x94d38d]

goroutine 1 [running]:
github.com/ethereum/go-ethereum/core/types.(*Block).NumberU64(...)
	github.com/ethereum/go-ethereum/core/types/block.go:292
github.com/ethereum/go-ethereum/core.(*BlockChain).SetHeadBeyondRoot(0xc0005c3200, 0x0, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
	github.com/ethereum/go-ethereum/core/blockchain.go:630 +0x20d
github.com/ethereum/go-ethereum/core.(*BlockChain).SetHead(0x656a2b, 0xc00033e000)
	github.com/ethereum/go-ethereum/core/blockchain.go:500 +0x27
github.com/ethereum/go-ethereum/core.(*BlockChain).ResetWithGenesisBlock(0xc0005c3200, 0xc0524c4000)
	github.com/ethereum/go-ethereum/core/blockchain.go:737 +0x5d
github.com/ethereum/go-ethereum/core.(*BlockChain).Reset(0x209e8e0)
	github.com/ethereum/go-ethereum/core/blockchain.go:730 +0x25
github.com/ethereum/go-ethereum/core.(*BlockChain).loadLastState(0xc0005c3200)
	github.com/ethereum/go-ethereum/core/blockchain.go:455 +0x1025
github.com/ethereum/go-ethereum/core.NewBlockChain({_, _}, _, _, {_, _}, {0x0, {0x0, 0x0}, 0x0, ...}, ...)
	github.com/ethereum/go-ethereum/core/blockchain.go:292 +0x9c5
github.com/ethereum/go-ethereum/eth.New(0xc0000d05b0, 0xc0005bb100)
	github.com/ethereum/go-ethereum/eth/backend.go:208 +0x1128
github.com/ethereum/go-ethereum/cmd/utils.RegisterEthService(0xc00052a780, 0xc0005bb100)
	github.com/ethereum/go-ethereum/cmd/utils/flags.go:1737 +0x18e
main.makeFullNode(0x1)
	github.com/ethereum/go-ethereum/cmd/geth/config.go:175 +0x1d2
main.geth(0xc0001586e0)
	github.com/ethereum/go-ethereum/cmd/geth/main.go:325 +0xb8
gopkg.in/urfave/cli%2ev1.HandleAction({0x12af020, 0x15ee8c0}, 0xc000124000)
	gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0x5a
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0003291e0, {0xc000132000, 0x17, 0x18})
	gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x5e6
main.main()
	github.com/ethereum/go-ethereum/cmd/geth/main.go:262 +0x35
````

Kindly check and help us

**Comment by atomlab** [comment]
The same issue. Full sync from network. Not from snapshot. 

```
# bor version
Bor
Version: 0.2.14-stable
Git Commit: 28963d5ccd3028e0ac6f1915845c747862d649d1
```
Options 
```
"bor",
"--cache 8192",
"--syncmode snap",
"--nat none",
"--datadir /data",
"--port 38336",
"--ws",
"--ws.addr 0.0.0.0",
"--ws.port 8036",
"--ws.origins=*",
"--http",
"--http.port 8136",
"--http.addr 0.0.0.0",
"--http.corsdomain=*",
"--http.vhosts=*",
"--bootnodes=enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303",
"--bor.heimdall=http://127.0.0.1:1317"
```

**Comment by sunil0410** [comment]
@julia-light  Thank you for reaching out to us.

We understand your concern.

Please help us with the below details

1. Are you facing any Bad Block Issues?
2. What's your Heimdall version?

**Comment by sunil0410** [comment]
@atomlab  Upon checking the details shared by you

1. We always recommend going with the syncomode = full 
2. Try using the snapshot we recommend the Prunned Snapshot.
3. Currently are you facing any Bad Block Issues?

**Comment by temaniarpit27** [comment]
Closing this as no further updates on this
