### ISSUE TITLE
bor exited after Error: invalid merkle root

### ISSUE THREAD

**Issue by Kur0x** [maticnetwork/bor#415]
#### System information

Bor version: `maticnetwork/bor:v0.2.14-tmp-span-hotfix` 
Heimdall version: `maticnetwork/heimdall:v0.2.9`
OS & Version: docker in OSX

#### Expected behaviour

I am running a polygon full node with bor-pruned-snapshot-2022-05-10.tar.gz.

#### Actual behaviour

Bor exited with error while syncing. I have tried multiply bor version 2.14 2.16 and 2.14-tmp-span-hotfix.

#### Steps to reproduce the behaviour

```
  bor:
    container_name: bor
    image: maticnetwork/bor:v0.2.14-tmp-span-hotfix
    # build: /data/github/bor
    volumes:
        - /Volumes/Data/bor:/root/.ethereum
    ports:
        - "8545:8545" # RPC
        - "30303:30303" # Peers (TCP)
        - "30303:30303/udp" # Peers (UDP)
    command:
        - bor
        - --datadir=/root/.ethereum
        - --syncmode=full
        - --bor-mainnet
        - --networkid=137
        - --bor.heimdall=http://heimdallr:1317
        - --bor.logs
        - --http
        - --http.addr=0.0.0.0
        - --http.port=8545
        - --http.api=admin,debug,eth,miner,net,personal,txpool,web3,bor
        - --ws
        - --ws.addr=0.0.0.0
        - --ws.port=8545
        - --ws.api=admin,debug,eth,miner,net,personal,txpool,web3,bor
        - --miner.gasprice=30000000000
        - --miner.gaslimit=20000000
        - --miner.gastarget=20000000
        - --bootnodes=enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303
        - --v5disc
```
#### Backtrace

[bor_err.log](https://github.com/maticnetwork/bor/files/8767046/bor_err.log)
````

 187: cumulative: 29975506 gas: 21000 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xcc3586d47ad4aa742b4309bef50dcd0e393dbad457f9ed67e7694d1f96239786 logs: [0xc004eb9290 0xc004eb9340] bloom: 00000000000000000000000000000000000000000000000000000000000000400000000000000000000000100000000000008000000000000000000000000000000000000000000000000000000000800000000000000000000100000000000000100000000000000800000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000400000000000000000000000000000000000000010004000000000000000000001000000000000000000000000800000108000000000000000000000000000000000000000000000000000020000000000000000100000 state: 



Error: invalid merkle root (remote: 7dba53282c928f139231fb3ec8b849560215d2d7bee7029708b1f9b04d0c2017 local: 82501e120d470404245de197c0ea2ba939527a6cd8a2774e97cabbb7b01cf574)

##############################

 

WARN [05-24|16:24:13.537] Synchronisation failed, retrying         err="no peers to keep download active"

WARN [05-24|16:24:13.543] Caller gas above allowance, capping      requested=9,223,372,036,854,775,807 cap=50,000,000

WARN [05-24|16:24:13.544] Caller gas above allowance, capping      requested=9,223,372,036,854,775,807 cap=50,000,000

INFO [05-24|16:24:13.545] Fetching state updates from Heimdall     fromID=2,056,621 to=2022-05-10T19:54:32Z

INFO [05-24|16:24:13.545] Fetching state sync events               queryParams="from-id=2056621&to-time=1652212472&limit=50"

INFO [05-24|16:24:13.555] → committing new state                   eventRecord="id 2056621, contract 0xA6FA4fB5f76172d178d61B04b0ecd319C5d1C0aa, data: 0x87a7811f4bfedea3d341ad165680ae306b01aaeacc205d227629cf157dd9f821000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000540583254046ed102b64db6417d49c856bee071b000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee00000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000eebd55c26eb9a, txHash: 0x4ae19b5a37cc9f09acb03f87fc74f54c9b6fca65ce0667f8ce0999da0d9f69d0, logIndex: 61, chainId: 137, time 2022-05-10T19:52:31Z"

INFO [05-24|16:24:13.556] → committing new state                   eventRecord="id 2056622, contract 0xA6FA4fB5f76172d178d61B04b0ecd319C5d1C0aa, data: 0x87a7811f4bfedea3d341ad165680ae306b01aaeacc205d227629cf157dd9f821000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000e034db422431b665301665516e60193365367bc2000000000000000000000000d0cd466b34a24fcb2f87676278af2005ca8a78c40000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000010ec1417e0297c2d3a8, txHash: 0xef88130445f71eaf8dd23b154a600a3256ddeed2bd01b07376a928127c5192ba, logIndex: 91, chainId: 137, time 2022-05-10T19:52:31Z"

INFO [05-24|16:24:13.556] → committing new state                   eventRecord="id 2056623, contract 0xA6FA4fB5f76172d178d61B04b0ecd319C5d1C0aa, data: 0x87a7811f4bfedea3d341ad165680ae306b01aaeacc205d227629cf157dd9f821000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000039a5753bbef2c287ce598a963dcb6230e110b563000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee00000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000001717b72f0a4000, txHash: 0x22986c5d8b1df6be9f074b081367f01342116c6a9089f00544ecfb2f28926dc2, logIndex: 86, chainId: 137, time 2022-05-10T19:52:31Z"

INFO [05-24|16:24:13.556] → committing new state                   eventRecord="id 2056624, contract 0xA6FA4fB5f76172d178d61B04b0ecd319C5d1C0aa, data: 0x87a7811f4bfedea3d341ad165680ae306b01aaeacc205d227629cf157dd9f821000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000003f07c29e3b7928faa5fab0b8fe2fa8a6aa1ce6d7000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000004f9471eb7a3de, txHash: 0x502d3f6d8663e4edf7c1c80020a4f57d0a910628bdbb03439c11e87e57045ed0, logIndex: 106, chainId: 137, time 2022-05-10T19:54:27Z"

INFO [05-24|16:24:13.557] → committing new state                   eventRecord="id 2056625, contract 0x8397259c983751DAf40400790063935a11afa28a, data: 0x00000000000000000000000069d10828233d7a656104455445d289bbfd50ef6d000000000000000000000000f635305d4e5214d4d3d34f56bde485215eaed9c200000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000140000000000000000000000000b8901acb165ed027e32754e0ffe830802919727f000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c4cc29a306000000000000000000000000e55ee4997c1bb8d10cda70da922eb8913b0a313300000000000000000000000000000000000000000000000010e7bbed4f4dac9700000000000000000000000000000000000000000000000010d56bf7f9722202000000000000000000000000000000000000000000000000000000006283fab20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, txHash: 0xa2ea413907c9b3d7a4c9ffcc65db7dd5e8da40eaad7932f9ecf17439ca62a7cb, logIndex: 3, chainId: 137, time 2022-05-10T19:54:27Z"

INFO [05-24|16:24:13.559] → committing new state                   eventRecord="id 2056626, contract 0xA6FA4fB5f76172d178d61B04b0ecd319C5d1C0aa, data: 0x87a7811f4bfedea3d341ad165680ae306b01aaeacc205d227629cf157dd9f821000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000007902cea88926c27f9f3d061539220bc39181a572000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee00000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000e90eda3944000, txHash: 0x496c3cc2c6bef130e5b7a5c20b9c5f1841a27a56636ae30f1019aad5148ede45, logIndex: 548, chainId: 137, time 2022-05-10T19:54:27Z"

INFO [05-24|16:24:13.559] → committing new state                   eventRecord="id 2056627, contract 0xA6FA4fB5f76172d178d61B04b0ecd319C5d1C0aa, data: 0x87a7811f4bfedea3d341ad165680ae306b01aaeacc205d227629cf157dd9f821000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000050852cf48c6b6dfd604214790eb95b7504f3e17e000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000021a17754eff194, txHash: 0xed5264f806bbf209dc315a46a9be68ea7c4a1569681bff6aaeb66ee9e2e678c6, logIndex: 64, chainId: 137, time 2022-05-10T19:54:27Z"

INFO [05-24|16:24:13.758] Unindexed transactions                   blocks=564  txs=12174 tail=25,814,352 elapsed=221.455ms

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xac141a]


goroutine 261716 [running]:

github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestorBinarySearch(0xc00a534000, 0xc0768b9930, 0x0, 0x1adc100, 0x1ac616f)

github.com/ethereum/go-ethereum/eth/downloader/downloader.go:966 +0x8da

github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc00a534000, 0xc0768b9930, 0x1e)

github.com/ethereum/go-ethereum/eth/downloader/downloader.go:818 +0x2ff

github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc00a534000, 0xc0768b9930, {0x9f, 0x84, 0x81, 0x26, 0x31, 0x81, 0x84, 0x9a, ...}, ...)

github.com/ethereum/go-ethereum/eth/downloader/downloader.go:475 +0x4de

github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc0245604e0, {0xc0bcfae700, 0xc0990ce8a0}, {0x9f, 0x84, 0x81, 0x26, 0x31, 0x81, 0x84, ...}, ...)

github.com/ethereum/go-ethereum/eth/downloader/downloader.go:431 +0x4b0

github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc00a534000, {0xc0bcfae700, 0x40}, {0x9f, 0x84, 0x81, 0x26, 0x31, 0x81, 0x84, ...}, ...)

github.com/ethereum/go-ethereum/eth/downloader/downloader.go:326 +0x5c

github.com/ethereum/go-ethereum/eth.(*handler).doSync(0xc009fcaa00, 0xc0b4d62880)

github.com/ethereum/go-ethereum/eth/sync.go:230 +0x1fd

github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync.func1()

github.com/ethereum/go-ethereum/eth/sync.go:206 +0x29

created by github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync

github.com/ethereum/go-ethereum/eth/sync.go:206 +0xaf

​
````

**Comment by 0xKrishna** [comment]
Is you heimdall working fine ?
Also don't use `--bor-mainnet` when you are using other flags anyway, I mean bor-mainnet might override some of your flags.

**Comment by Kur0x** [comment]
my heimdall is still running. But the command `curl -s http://localhost:26657/status` stucked.
Here is heimdall log
[heimdall.log](https://github.com/maticnetwork/bor/files/8770445/heimdall.log)
.

**Comment by Kur0x** [comment]
I run bor again without `--bor-mainnet` and use the same docker for heimdall. It run into error again.
[bor_err.log](https://github.com/maticnetwork/bor/files/8772031/bor_err.log)

```
Error: invalid merkle root (remote: 40d81473f2f67fe60405b17be4a84ad38ef09509768974af7971698b713e6267 local: 9bd29dcdce600588f7d31c94629a5158742cf976aceb5df184ee9d6c1e1384d5)
##############################

WARN [05-25|13:01:08.724] Synchronisation failed, retrying         err="no peers to keep download active"
INFO [05-25|13:01:08.947] Unindexed transactions                   blocks=1953 txs=34247 tail=25,814,599 elapsed=231.258ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xaecdb3]

goroutine 139064 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestorBinarySearch(0xc009f9aa80, 0xc08317e0d0, 0x0, 0x1adc1f7, 0x1ac6266)
	github.com/ethereum/go-ethereum/eth/downloader/downloader.go:966 +0x8d3
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc009f9aa80, 0xc08317e0d0, 0x1e?)
	github.com/ethereum/go-ethereum/eth/downloader/downloader.go:818 +0x2ff
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc009f9aa80, 0xc08317e0d0, {0xbf, 0xf0, 0x70, 0x2d, 0x32, 0x10, 0xf0, 0xa6, ...}, ...)
	github.com/ethereum/go-ethereum/eth/downloader/downloader.go:475 +0x4a6
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0x6773480737db1706?, {0xc082c21f40, 0x40}, {0xbf, 0xf0, 0x70, 0x2d, 0x32, 0x10, 0xf0, ...}, ...)
	github.com/ethereum/go-ethereum/eth/downloader/downloader.go:431 +0x498
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc009f9aa80, {0xc082c21f40, 0x40}, {0xbf, 0xf0, 0x70, 0x2d, 0x32, 0x10, 0xf0, ...}, ...)
	github.com/ethereum/go-ethereum/eth/downloader/downloader.go:326 +0x5c
github.com/ethereum/go-ethereum/eth.(*handler).doSync(0xc025ff0000, 0xc051203a40)
	github.com/ethereum/go-ethereum/eth/sync.go:230 +0x213
github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync.func1()
	github.com/ethereum/go-ethereum/eth/sync.go:206 +0x29
created by github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync
	github.com/ethereum/go-ethereum/eth/sync.go:206 +0xaa
```

**Comment by ruXlab** [comment]
I came across the same issue after no space left on the disk. Resolved by downloading the recent pruned snapshot from https://snapshots.matic.today

hint: it's possible to unarchive while downloading:

In the: ` ~/.bor/data/bor/bor/chaindata`:

```
https://matic-blockchain-snapshots.s3-accelerate.amazonaws.com/matic-mainnet/bor-pruned-snapshot-2022-05-17.tar.gz | tar -xzf -
```

**Comment by 0xKrishna** [comment]
Closing this for now, Follow the above solution, If doesn't work please re-open.
