### ISSUE TITLE
panic: bor flag redefined: goerli

### ISSUE THREAD

**Issue by mikhail-khalizev** [maticnetwork/bor#990]
Our support team has aggregated some common issues and their solutions from past which are faced while running or interacting with a bor client. In order to prevent redundant efforts, we would encourage you to have a look at the [FAQ's section](https://wiki.polygon.technology/docs/faq/technical-faqs/) of our documentation mentioning the same, before filing an issue here. In case of additional support, you can also join our [discord](https://discord.com/invite/zdwkdvMNY2) server

#### **System information**

Bor client version: v0.5.0 
OS & Version: Linux

#### **Overview of the problem**

`bor` immediately fails after start.

#### **Reproduction Steps**

```
> git clone --depth 1 --branch v0.5.0 https://github.com/maticnetwork/bor.git
> cd bor
> make geth
```
```
> ./build/bin/geth
geth flag redefined: goerli
panic: geth flag redefined: goerli

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0003547e0, {0x33549d0, 0xc00077f6b0}, {0xc000791838, 0x6}, {0x27ae775, 0x3e})
        flag/flag.go:1028 +0x3a5
github.com/urfave/cli/v2.(*BoolFlag).Apply(0x4658700, 0x21fb9c0?)
        github.com/urfave/cli/v2@v2.17.2-0.20221006022127-8f469abc00aa/flag_bool.go:136 +0x3cc
github.com/urfave/cli/v2.flagSet({0x7ffe5e642ee8, 0x4}, {0xc000569000, 0xb5, 0x413fa5?})
        github.com/urfave/cli/v2@v2.17.2-0.20221006022127-8f469abc00aa/flag.go:166 +0xef
github.com/urfave/cli/v2.(*App).newFlagSet(...)
        github.com/urfave/cli/v2@v2.17.2-0.20221006022127-8f469abc00aa/app.go:242
github.com/urfave/cli/v2.(*App).RunContext(0xc000988a80, {0x3363340?, 0x4ae8b20}, {0xc0000520d0, 0x1, 0x1})
        github.com/urfave/cli/v2@v2.17.2-0.20221006022127-8f469abc00aa/app.go:269 +0x147
github.com/urfave/cli/v2.(*App).Run(...)
        github.com/urfave/cli/v2@v2.17.2-0.20221006022127-8f469abc00aa/app.go:252
main.main()
        github.com/ethereum/go-ethereum/cmd/geth/main.go:278 +0x45
```

**Comment by mikhail-khalizev** [comment]
`make bor` solves the problem
